urls.py
from django.conf.urls.defaults import *
from django.conf import settings
from django.views.generic import RedirectView
from django.views.generic import TemplateView
# Uncomment the next two lines to enable the admin:
from django.views.generic import RedirectView
from django.views.generic import TemplateView

from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
admin.autodiscover()

urlpatterns = patterns('',
  # For admin
  url(r'^admin/', include(admin.site.urls)),

  # For widget
  url(r'^widget/(.{,25})/$', 'rb.views.widget'),
  url(r'^widgetCss/', 'rb.views.widgetCss'),
  
  # For Facebook
  url(r'^fb/$', 'rb.views.fb'),
  url(r'^fblogin/$', 'rb.views.fblogin'),
  url(r'^xdm_status/$', 'rb.views.xdm_status'),
  url(r'^fb_channel/$', 'rb.views.fb_channel'),
  
  # For short URL expander
  url(r'^s/(?P<short>[0-9a-zA-Z]+)/$', 'rb.views.expander'),
  url(r'^i/(?P<short>[0-9]+)/$', 'rb.views.interaction_redirect'),
  
  
  # For main website
  url(r'^$', 'rb.views.home'),
  url(r'^see/$', 'rb.views.see'),
  #url(r'^$', 'rb.views.main', kwargs={"view":"index", "filtered":"charcoal"}),

  url(r'^unfiltered/$', 'rb.views.main', kwargs={"view":"index"}),
  url(r'^stream/$', 'rb.views.main', kwargs={"view":"index"}),
  url(r'^tags/$', 'rb.views.main', kwargs={"view":"tags"}),
  url(r'^comments/$', 'rb.views.main', kwargs={"view":"comments"}),
  url(r'^shares/$', 'rb.views.main', kwargs={"view":"shares"}),
  
  # Client Facing Registration & Settings
  url(r'^settings/$', 'rb.views.settings'),
  url(r'^register/$', 'rb.views.group'),
  url(r'^sites/$', 'rb.views.sites'),
  # url(r'^settings/(?P<short_name>[\w\-\.]+)/$', 'rb.views.settings'),
  url(r'^group/(?P<short_name>[\w\-\.]+)/settings/$', 'rb.views.settings'),
  # url(r'^(?P<short_name>[\w\-\.]+)/settings/$', 'rb.views.settings'),
  url(r'^settings_wordpress/(?P<short_name>[\w\-\.]+)/$', 'rb.views.settings_wordpress'),


  # User profile pages
  url(r'^user/(?P<user_id>\d+)/$', 'rb.views.main'),
  url(r'^user/(?P<user_id>\d+)/tags/$', 'rb.views.main', kwargs={"view":"tags"}),
  url(r'^user/(?P<user_id>\d+)/comments/$', 'rb.views.main', kwargs={"view":"comments"}),
  url(r'^user/(?P<user_id>\d+)/shares/$', 'rb.views.main', kwargs={"view":"shares"}),
  url(r'^user/(?P<user_id>\d+)/bookmarks/$', 'rb.views.main', kwargs={"view":"bookmarks"}),
  
  url(r'^follows/(?P<user_id>\d+)/$', 'rb.views.follow_interactions'),
  
  url(r'^board_create/$', 'rb.views.create_board'),
  url(r'^board/(?P<board_id>\d+)/', 'rb.views.board'),
  
  
  # Specific page
  url(r'^page/(?P<page_id>\d+)/$', 'rb.views.main'),
  url(r'^page/(?P<page_id>\d+)/not_approved/$', 'rb.views.main', kwargs={"admin":"not_approved"}),
  url(r'^page/(?P<page_id>\d+)/tags/$', 'rb.views.main', kwargs={"view":"tags"}),
  url(r'^page/(?P<page_id>\d+)/comments/$', 'rb.views.main', kwargs={"view":"comments"}),
  url(r'^page/(?P<page_id>\d+)/shares/$', 'rb.views.main', kwargs={"view":"shares"}),
  url(r'^page/(?P<page_id>\d+)/bookmarks/$', 'rb.views.main', kwargs={"view":"bookmarks"}),
  url(r'^page/(?P<page_id>\d+)/reset/$', 'rb.views.resetPageData' ),

  # Specific site
  url(r'^site/(?P<site_id>\d+)/$', 'rb.views.main'),
  url(r'^site/(?P<site_id>\d+)/not_approved/$', 'rb.views.main', kwargs={"admin":"not_approved"}),
  url(r'^site/(?P<site_id>\d+)/tags/$', 'rb.views.main', kwargs={"view":"tags"}),
  url(r'^site/(?P<site_id>\d+)/comments/$', 'rb.views.main', kwargs={"view":"comments"}),
  url(r'^site/(?P<site_id>\d+)/shares/$', 'rb.views.main', kwargs={"view":"shares"}),
  url(r'^site/(?P<site_id>\d+)/bookmarks/$', 'rb.views.main', kwargs={"view":"bookmarks"}),

  # Specific group
  url(r'^group/(?P<short_name>[\w\-\.]+)/$', 'rb.views.main'),
  url(r'^group/(?P<short_name>[\w\-\.]+)/not_approved/$', 'rb.views.main', kwargs={"admin":"not_approved"}),
  url(r'^group/(?P<short_name>[\w\-\.]+)/tags/$', 'rb.views.main', kwargs={"view":"tags"}),
  url(r'^group/(?P<short_name>[\w\-\.]+)/comments/$', 'rb.views.main', kwargs={"view":"comments"}),
  url(r'^group/(?P<short_name>[\w\-\.]+)/shares/$', 'rb.views.main', kwargs={"view":"shares"}),
  url(r'^group/(?P<short_name>[\w\-\.]+)/bookmarks/$', 'rb.views.main', kwargs={"view":"bookmarks"}), 
  
  #single interaction
  url(r'^interaction/(?P<interaction_id>\d+)/$', 'rb.views.main'),
  
  # Main Site Supporting Pages
  url(r'^team/$', 'rb.views.team'),
  url(r'^faq/$', 'rb.views.faq'),
  url(r'^terms/$', 'rb.views.terms'),
  url(r'^privacy/$', 'rb.views.privacy'),
  url(r'^react/$', 'rb.views.react'),
  url(r'^publishers/$','rb.views.learn'),
  url(r'^retailers/$','rb.views.retailers'),
  url(r'^about/$','rb.views.about'),
  url(r'^learn/$','rb.views.learn'),
  
  # changed to rb.views.friendlylogin instead of rb.views.login, because login sometimes throws an error.
  # the error is 'str' object has no attribute 'status_code' 
  # and it seems to be caused by the request.META.get('HTTP_REFERER') code, which I don't understand why we want in there.
  # fix this after we investegate and understand.
  url(r'^login/$', 'rb.views.friendlylogin'),
  url(r'^friendlylogin/$', 'rb.views.friendlylogin'),
  url(r'^friendlylogin_wordpress/$', 'rb.views.friendlylogin_wordpress'),
  
  # Sidebar
  url(r'^sidebar/$', 'rb.views.sidebar'),
  url(r'^sidebar/user/(?P<user_id>\d+)/$', 'rb.views.sidebar'),
  url(r'^sidebar/group/(?P<short_name>[\w\-\.]+)/$', 'rb.views.sidebar'),
  #url(r'^cards/(?P<group_id>\d/$', 'rb.views.cards'),

  # Extras
  url(r'^favicon\.ico$', RedirectView.as_view(url='/static/site/images/favicon.ico')),

  # API
  url(r'^api/', include('readrboard.api.urls')),
  
  # CHRONS API
  url(r'^chronos/', include('readrboard.chronos.urls')),
  
  
  # Group Supporting Pages
  # dont expose the signup form anymore for now.  We'll use the wufoo form and onboard ourselves - redirect them.
  # url(r'^signup/$', 'rb.views.create_group'),
  url(r'^manage/', 'rb.views.manage_groups'),
  url(r'^signup/$', RedirectView.as_view(url='/about/#publishers')),
  url(r'^signup_wordpress/$', 'rb.views.create_group_wordpress'),
  url(r'^group/(?P<short_name>[\w\-\.]+)/blocked_reactions/$', 'rb.views.group_blocked_tags'),
  url(r'^group/(?P<short_name>[\w\-\.]+)/all_reactions/$', 'rb.views.group_all_tags'),
  url(r'^group/(?P<short_name>[\w\-\.]+)/analytics', include('readrboard.analytics.urls')),
  url(r'^group/(?P<short_name>[\w\-\.]+)/analytics_v1', include('readrboard.analytics.urls_v1')),
  url(r'^group/(?P<short_name>[\w\-\.]+)/admin_request/$', 'rb.views.admin_request'),

  url(r'^group/(?P<short_name>[\w\-\.]+)/admin_approve/$', 'rb.views.admin_approve'),
  url(r'^group/(?P<short_name>[\w\-\.]+)/admin_approve/(?P<request_id>\d+)/$', 'rb.views.admin_approve'),

  #inhouse
  url(r'^analytics', include('readrboard.analytics.urls')),
  url(r'^analytics_v1', include('readrboard.analytics.urls_v1')),


  # Plugin Settings
  url(r'^wordpress/$', 'rb.views.wordpress'),
  url(r'^wordpress_edit/$', 'rb.views.wordpress_edit'),
  
  # User creation and registration
  url(r'^user_create/$', 'rb.views.create_rb_user'),
  url(r'^confirmemail/$', 'rb.views.confirm_rb_user'),
  url(r'^reset_password/$', 'rb.views.reset_rb_password'),
  url(r'^change_password/$', 'rb.views.change_rb_password'),
  url(r'^request_password/$', 'rb.views.request_password_reset'),
  url(r'^user_modify/$', 'rb.views.modify_rb_social_user'),
  
  url(r'^rb_login/$', 'rb.views.rb_login'),
  url(r'^rb_login_success/$', 'rb.views.rb_login_success'),
  # For demos
  #url(r'^demo/', settings.STATIC_URL)
)

from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += url(r'^static/engage\.js$', RedirectView.as_view(url='/static/engage_full.js')),

urlpatterns += patterns('django.contrib.staticfiles.views',
        url(r'^static/(?P<path>.*)$', 'serve'),        
    ) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    
    
    

rb/models.py
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.db.models import Count
#from treebeard.mp_tree import MP_Node
from django.contrib.auth.models import User
from baseconv import base62_encode
import datetime


"""
Custom Managers
"""
class TagManager(models.Manager):
    def get_query_set(self):
        return super(TagManager, self).get_query_set().filter(kind='tag')

class CommentManager(models.Manager):
    def get_query_set(self):
        return super(CommentManager, self).get_query_set().filter(kind='com')

class InteractionManager(models.Manager):
    def node_count(self):
        subquery = """(SELECT node.body, Count(interaction_node_id) AS count 
                       FROM rb_interaction AS interaction, rb_interactionnode AS node
                       GROUP BY interaction_node_id) AS interaction_count"""
        condition = 'interaction.interaction_node_id = node.id' # Join
        order = '-count'
        return self.get_query_set().extra(
            tables=[subquery],
            where=[condition]).order_by(order
        )

"""
Abstract Models
"""
class DateAwareModel(models.Model):
    created = models.DateTimeField(auto_now_add=True, editable=False)
    modified = models.DateTimeField(auto_now=True, editable=False) 

    class Meta:
        abstract = True

class UserAwareModel(models.Model):
    user = models.ForeignKey(User)

    class Meta:
        abstract = True

"""
ReadrBoard Models
"""
class InteractionNode(models.Model):
    body = models.TextField()
    #hash = models.CharField(max_length=32, unique=True, db_index=True)
    
    def natural_key(self):
        return self.body
    
    def tag_count(self, page=None, content=None):
        tags = self.interaction_set.filter(kind='tag')
        if page: tags = tags.filter(page=page)
        if content: tags = tags.filter(content=content)
        
        return len(tags)
    
    def __unicode__(self):
        return u'ID: {0}, Body: {1}'.format(self.id, self.body[:25])

class Feature(models.Model):
    text = models.BooleanField(editable=False)
    images = models.BooleanField(editable=False)
    flash = models.BooleanField(editable=False)

    class Meta:
        unique_together = ('text','images','flash')

    def __unicode__(self):
        return u'Feature(Text: {0}, Images: {1}, Flash: {2})'.format(self.text, self.images, self.flash)

import os
def get_image_path(instance, filename):
    return os.path.join('users/', str(instance.id) +'/avatars/', filename)


class SocialUser(models.Model):
    GENDER_CHOICES = (
        ('M', 'Male'),
        ('F', 'Female'),
    )

    # For Privacy
    private_profile = models.BooleanField(default=False)
    follow_email_option = models.BooleanField(default=True)
    notification_email_option = models.BooleanField(default=True)
    
    
    """Social Auth association model"""
    user = models.OneToOneField(User, related_name='social_user', unique=True)
    provider = models.CharField(max_length=32)
    uid = models.CharField(max_length=255, unique=True)
    full_name = models.CharField(max_length=255)

    # Might not get these -> blank=True
    username = models.CharField(max_length=255, blank=True, null=True)
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES, blank=True, null=True)
    hometown = models.CharField(max_length=255, blank=True, null=True)
    bio = models.TextField(max_length=255, blank=True, null=True)
    img_url = models.URLField(blank=True)
    
    avatar = models.ImageField(upload_to=get_image_path, blank=True, null=True)
    
    default_tags = models.ManyToManyField(InteractionNode, through='UserDefaultTag')

    def admin_groups_unapproved(self):
        ga = GroupAdmin.objects.filter(social_user=self, approved=False)
        return Group.objects.filter(id__in=ga.values('group'))
    
    def admin_groups(self):
        ga = GroupAdmin.objects.filter(social_user=self, approved=True)
        return Group.objects.filter(id__in=ga.values('group'))
        
    def admin_group(self):
        return self.admin_groups()[0]

    def __unicode__(self):
        return self.user.username

    class Meta:
        unique_together = ('provider', 'uid', 'username')

class Product(models.Model):
    # just using text fields.  postgre does not care (http://stackoverflow.com/questions/7354588/django-charfield-vs-textfield) and mysql, well, whatever  -- pb.
    # all from schema.org ProductModel -- http://schema.org/ProductModel
    additionalType              = models.TextField(blank=True, null=True)
    alternateName               = models.TextField(blank=True, null=True)
    description                 = models.TextField(blank=True, null=True)
    image                       = models.TextField(blank=True, null=True)
    name                        = models.TextField(blank=True, null=True)
    sameAs                      = models.TextField(blank=True, null=True)
    url                         = models.TextField(blank=True, null=True)
    aggregateRating_ratingValue             = models.TextField(blank=True, null=True)
    brand_name                       = models.TextField(blank=True, null=True)
    color                       = models.TextField(blank=True, null=True)
    gtin13                      = models.TextField(blank=True, null=True)
    gtin14                      = models.TextField(blank=True, null=True)
    gtin8                       = models.TextField(blank=True, null=True)
    logo                        = models.TextField(blank=True, null=True)
    manufacturer                = models.TextField(blank=True, null=True)
    model                       = models.TextField(blank=True, null=True)
    mpn                         = models.TextField(blank=True, null=True)
    offers_price                      = models.TextField(blank=True, null=True)
    offers_priceCurrency                      = models.TextField(blank=True, null=True)
    productID                   = models.TextField(blank=True, null=True)
    releaseDate                 = models.TextField(blank=True, null=True)
    sku                         = models.TextField(blank=True, null=True)
    weight                      = models.TextField(blank=True, null=True)
    width                       = models.TextField(blank=True, null=True)
    
    def __unicode__(self):
        return self.name
        
    # class Meta:
    #     ordering = ['name']

class Group(models.Model):
    name = models.CharField(max_length=250)
    short_name = models.CharField(max_length=50, unique=True)
    language = models.CharField(max_length=25, default="en")
    approved = models.BooleanField(default=False)
    requires_approval = models.BooleanField(default=False)
    signin_organic_required = models.BooleanField(default=False)
    demo_group = models.BooleanField(default=False)
    word_blacklist = models.TextField(blank=True)
    paragraph_helper = models.BooleanField(default=True)
    media_url_ignore_query = models.BooleanField(default=True)
    
    # is premium?
    premium = models.BooleanField(default=False)
    send_notifications = models.BooleanField(default=True)

    # Customization
    call_to_action = models.CharField(max_length=255, default='', blank=True)
    media_display_pref = models.CharField(max_length=25, default='', blank=True)
    
    # Jquery settings
    inline_selector = models.CharField(max_length=100, default='', blank=True)
    inline_func = models.CharField(max_length=25, default='', blank=True)

    # new attributes for data dashboard.  all are form fields to support page settings.
    author_selector = models.CharField(max_length=255, blank=True) # jquery()
    author_attribute = models.CharField(max_length=255, blank=True) # jquery .attr()
    topics_selector = models.CharField(max_length=255, blank=True) # jquery()
    topics_attribute = models.CharField(max_length=255, blank=True) # jquery .attr()
    section_selector = models.CharField(max_length=255, blank=True)  # jquery()
    section_attribute = models.CharField(max_length=255, blank=True)  # jquery .attr()

    # mobile settings
    hideOnMobile = models.BooleanField(default=False)
    hideDoubleTapMessage = models.BooleanField(default=False)
    doubleTapMessage = models.TextField(blank=True)
    doubleTapMessagePosition = models.CharField(max_length=25, default='bottom')
    
    # Many to many relations
    admins = models.ManyToManyField(SocialUser, through='GroupAdmin')
    blessed_tags = models.ManyToManyField(InteractionNode, through='GroupBlessedTag', related_name = 'Blessed Tag')

    blocked_tags = models.ManyToManyField(InteractionNode, through='BlockedTag', related_name = 'Blocked Tag')
    all_tags = models.ManyToManyField(InteractionNode, through='AllTag', related_name = 'All Tag')

    
    # black/whitelist fields
    active_sections = models.CharField(max_length=255, blank=True)
    anno_whitelist = models.CharField(max_length=255, blank=True, default=u"p,img")
    img_whitelist = models.CharField(max_length=255, blank=True)
    img_blacklist = models.CharField(max_length=255, blank=True)
    no_readr = models.CharField(max_length=255, blank=True)
    post_selector = models.CharField(max_length=255, blank=True)
    post_href_selector = models.CharField(max_length=255, blank=True)
    summary_widget_selector = models.CharField(max_length=255, blank=True)
    summary_widget_method = models.CharField(max_length=255, blank=True)
    br_replace_scope_selector = models.CharField(max_length=255, blank=True)
    separate_cta = models.CharField(max_length=255, blank=True)
    
    # logo fields
    logo_url_sm = models.CharField(max_length=200, blank=True)
    logo_url_med = models.CharField(max_length=200, blank=True)
    logo_url_lg = models.CharField(max_length=200, blank=True)

    # features
    share = models.ForeignKey(Feature, related_name = 'Share Feature', default=1)

rb/templates/popup-forms/password_change.html
{% extends "popup_form.html" %}

{% block mainContent %}
  <h1>ReadrBoard Password Reset</h1>
  <div class="container">
  {% if requested %}
    <h3>Thanks!</h3>
    <a href = "/">Home</a>
  {% else %}

      <form class="popupForm" action="/reset_password/" enctype="multipart/form-data" method="post" class="in-page">
        <div class="formBody clearfix">
            {% csrf_token %}
          
            {{ form.non_field_errors }}
            {{ form.errors }}

            <div class='formBodySection'>
                <label for="id_password">Password</label>
                {{ form.password }}{{ form.password.errors }}
            </div>
            <div class='formBodySection'>
                <label for="id_password2">Password Again</label>
                {{ form.password2 }}{{ form.password2.errors }}
            </div>
            <div>
                {{ form.password_token }} {{ form.password_token.errors }}
            </div>
            <div>
                {{ form.uid }} {{ form.uid.errors }}
            </div>

        </div>
        <button class="btn" type="submit">Submit</button>
    </form>

  {% endif %}
    </div>
{% endblock mainContent %}

rb/templates/popup-forms/password_change_loggedin.html
{% extends "popup_form.html" %}

{% block mainContent %}
  <h1>Change Your ReadrBoard Password</h1>
  <div class="container" style="max-width:350px;">
  {% if requested %}
    <h3>Your password has been changed successfully!</h3>
    <a href = "/">Home</a>
  {% else %}
<style>
label { display:block; }
</style>
      <form class="popupForm" action="/change_password/" enctype="multipart/form-data" method="post" class="in-page">
        <div class="formBody clearfix">
            {% csrf_token %}
          
            {{ form.non_field_errors }}
            {{ form.errors }}

            <div class='formBodySection'>
                <label for="id_password">Password</label>
                {{ form.password }}{{ form.password.errors }}
            </div>
            <div class='formBodySection'>
                <label for="id_password2">Password Again</label>
                {{ form.password2 }}{{ form.password2.errors }}
            </div>
            <div>
                {{ form.uid }} {{ form.uid.errors }}
            </div>

        </div>
        <button class="btn" type="submit">Submit</button>
    </form>

  {% endif %}
    </div>
{% endblock mainContent %}

rb/templates/popup-forms/password_reset.html
{% extends "popup_form.html" %}

{% block mainContent %}
  <h1>Password Reset</h1>
  <div class="container" style="max-width:400px;">
  {% if requested %}
    <h3>Thanks!  We have sent you an email with a link to complete your password change.</h3>
    <a href = "/">Home</a>
  {% else %}
    <div class="userFeedbackMsg">
        <h3>Enter your user name or your email address, and we'll email you a link to reset your password.</h3>
    </div>
    <form class="popupForm" action="/request_password/" enctype="multipart/form-data" method="post" class="in-page">
        <div class="formBody clearfix">
            {% csrf_token %}

            {% if message %}<div class="error">{{ message }}</div>{% endif %}
            <div class='formBodySection'>
                <label>User Name:</label>
                <input type="text" name="username" />
            </div>
            <div class='formBodySection'>
                <label>Email address:</label>
                <input type="text" name="email" />
            </div>
        </div>
        <button class="btn" type="submit">Submit</button>
    </form>
  {% endif %}
  </div>
{% endblock mainContent %}

rb/templates/popup-forms/rb_login.html
{% extends "popup_form.html" %}

{% block mainContent %}

  <h1>Log In</h1>
  {% csrf_token %}
  <div class="container">
    <div id="errorMsgWrap"></div>
    <div id="direct_registration" class="formBody clearfix">
  		<div class='formBodySection grid-whole'>
  			<div class="grid-half"><label>User Name</label></div>
            <div class="grid-half">
    			<input type="text" name="username" tabindex="1" />
    			<a class="alternateAction" href="javascript:void(0);" onclick="createNewAccount();" style="font-size:11px;font-style:italic;">Create New Account &raquo;</a>
            </div>
		</div>
		<div class='formBodySection grid-whole'>
	  		<div class="grid-half"><label>Password</label></div>
            <div class="grid-half">
                <input type="password" name="password" tabindex="2" />
                <a class="alternateAction" href="javascript:void(0);" onclick="forgotPassword();" style="font-size:11px;font-style:italic;">Forgot Password? &raquo;</a>
            </div>
		</div>
	</div>
	<button class="btn" onclick="direct_registration();" tabindex="3" id="submit_login">Log In</button>
	<script type="text/javascript">

		RDRAuth.events.track('show_login_form');
        RDRAuth.events.trackEventToCloud({
            category: 'login',
            action: 'show_form',
            opt_label: 'auth: rb'
        });

		$('input[name="username"]').focus();
		$('#groupname').text( decodeURI(qs_args.group_name) );

		$('#direct_registration input').keyup( function(event) {
            if (event.keyCode == '13') { //enter.  
            	$('#submit_login').click();
            }
        });
		
		window.opener.RDRAuth.checkRBLoginWindow();

		function direct_registration() {
			var sendData = "username="+$('#direct_registration').find('input[name="username"]').val()+
						   "&password="+$('#direct_registration').find('input[name="password"]').val();

			$.ajax({
				beforeSend: function( xhr ) {
					xhr.setRequestHeader("X-CSRFToken", $.cookie('csrftoken') );
				},
				url: "/api/rb/",
				type: "post",
				contentType: "application/x-www-form-urlencoded",
				dataType: "json",
				data: sendData,
				success: function(response) {
					if ( response.data ) {
						if ( response.data.status == "fail" ) {
							$('#errorMsgWrap').html('<div class="error">'+response.data.message+'</div>')
                                .hide()
                                .fadeIn();
						} else {
							RDRAuth.setUser(response);
                            
                            window.location.href=RDR_baseUrl+'/rb_login_success/';
						}
					}
				}
			});
		}

        function createNewAccount(){
            var w = 535;
            /*made higher to account for 'required fields' message*/
            var h = 350;
            var l = (window.screen.width/2)-(w/2);
            var t = (window.screen.height/2)-(h/2);

            var properties = 'menubar=1,scrollbars=yes,resizable=1,width='+w+',height='+h+',top='+t+',left='+l;

            window.open(
                RDR_baseUrl+'/user_create/',
                'readr_create_user',
                properties
            );
            window.close();
            return false;
        }
        
        function forgotPassword () {
            var w = 535;
            var h = 300;
            var l = (window.screen.width/2)-(w/2);
            var t = (window.screen.height/2)-(h/2);

            var properties = 'menubar=1,scrollbars=yes,resizable=1,width='+w+',height='+h+',top='+t+',left='+l;

            window.open(
                RDR_baseUrl+'/request_password/',
                'readr_forgot_pw',
                properties
            );
            window.close();
            return false;
        }

	</script>
  </div>
{% endblock mainContent %}

rb/templates/popup-forms/rb_login_success.html
{% extends "popup_form.html" %}

{% block mainContent %}

  <h1>Welcome Back!</h1>
  <h1>{{ user }}</h1>
  {% csrf_token %}
  <div class="container">
  	You can <a href="javascript:void(0);" onclick="self.close();">close this window</a>.
	<script type="text/javascript">
		RDRAuth.events.track('login_success_page');
        RDRAuth.events.trackEventToCloud({
            category: 'login',
            action: 'success',
            opt_label: 'auth: rb'
        });
        
		self.close();
	</script>
  </div>
{% endblock mainContent %}

rb/templates/popup-forms/social_user_modify.html
{% extends "popup_form.html" %}

{% block mainContent %}
  <h1>Change User Avatar</h1>
  <div class="container">
        {% if requested %}
            <h3>Thanks!</h3>
            <a href = "/">Home</a>
        {% else %}
    
        <form class="popupForm" action="/user_modify/" enctype="multipart/form-data" method="post" class="in-page">
            <div class="formBody clearfix">
                {% csrf_token %}
                {{ form.non_field_errors }}
                {{ form.errors }}

                <div class='formBodySection'>
                    <label for="id_avatar">Avatar </label>
                    {{ form.avatar }}{{ form.avatar.errors }}
                </div>
                <div>
                    {{ form.user_token }} {{ form.user_token.errors }}
                </div>
                <div>
                    {{ form.id }} {{ form.id.errors }}
                </div>

            </div>
            <button class="btn" type="submit">Submit</button>
        </form>

    </div>
  {% endif %}
{% endblock mainContent %}

rb/templates/popup-forms/user_confirm.html
{% extends "popup_form.html" %}

{% block mainContent %}
  {% if confirmed %}
  <h1>Thanks for confirming your account.</h1>
  <div style="margin:20px;">
        <h3>Welcome to <a href = "/">ReadrBoard</a></h3>
    </div>
    {% else %}
    <h1>It looks like you still need to confirm your account.</h1>
      <div style="margin:20px;">
        <h3>Please see your email inbox for a confirmation link.</h3>
    </div>
    {% endif %}

{% endblock mainContent %}